# Site settings
title: 年费闹钟
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "小程序·大作为"  
baseurl: ""
url: "http://www.iminiapp.com"  

# About/contact
owner: 
  name: "Daniel Young"
  email: ylming2011@126.com
  bio: "小而精"

# Data
gavatar: 
favicon: 

douban_username:  
twitter_username: 
github_username: iminiapp
facebook_username: 
weibo_username:  "千叶树Daniel"
zhihu_username: 

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Beijing

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Daniel Young"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : daniel
  disqus :
      short_name : daniel

# Analytics and webmaster tools stuff goes here
google_analytics: UA-88005615-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation